### ISSUE TITLE
Sample app throws glError 1285 when I press Record button

### ISSUE THREAD

**Issue by patolax** [spaceLenny/recordablesurfaceview#18]
Sample app throws glError 1285 when I press Record button. App crashes but it renders shapes to the screen.

2020-11-06 17:51:03.900 22354-22396/? E/MyGLRenderer: glGetUniformLocation: glError 1285
2020-11-06 17:51:03.907 22354-22396/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.android.opengl, PID: 22354
    java.lang.RuntimeException: glGetUniformLocation: glError 1285
        at com.example.android.opengl.MyGLRenderer.checkGlError(MyGLRenderer.java:146)
        at com.example.android.opengl.Square.draw(Square.java:136)
        at com.example.android.opengl.MyGLRenderer.onDrawFrame(MyGLRenderer.java:73)
        at com.example.android.opengl.MyGLSurfaceView.onDrawFrame(MyGLSurfaceView.java:108)
        at com.uncorkedstudios.android.view.recordablesurfaceview.RecordableSurfaceView$ARRenderThread.run(RecordableSurfaceView.java:610)
2020-11-06 17:51:33.120 22473-22527/com.example.android.opengl E/MyGLRenderer: glGetUniformLocation: glError 1285
2020-11-06 17:51:33.125 22473-22527/com.example.android.opengl E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.example.android.opengl, PID: 22473
    java.lang.RuntimeException: glGetUniformLocation: glError 1285
        at com.example.android.opengl.MyGLRenderer.checkGlError(MyGLRenderer.java:146)
        at com.example.android.opengl.Square.draw(Square.java:136)
        at com.example.android.opengl.MyGLRenderer.onDrawFrame(MyGLRenderer.java:73)
        at com.example.android.opengl.MyGLSurfaceView.onDrawFrame(MyGLSurfaceView.java:108)
        at com.uncorkedstudios.android.view.recordablesurfaceview.RecordableSurfaceView$ARRenderThread.run(RecordableSurfaceView.java:610)

**Comment by spaceLenny** [comment]
Does this still occur? These issues tend to arise from bad ordering of gl creation, or weird timing on attaching to the window.

**Comment by patolax** [comment]
I have released the app all crashes are related to RecordableSurfaceView.java in deferent android versions and devices. 
Any ideas as to how to resolve these?

```
prepare failed.
android.media.MediaRecorder._prepare (MediaRecorder.java)
android.media.MediaRecorder.prepare (MediaRecorder.java:882)
com.time.fog.base.view.RecordableSurfaceView.initRecorder (RecordableSurfaceView.java:331)
com.time.fog.base.view.RecordableSurfaceView.initRecorder (RecordableSurfaceView.java:239)
com.time.fog.fragments.VideoFragment.setupRecorder (VideoFragment.java:239)
com.time.fog.fragments.VideoFragment.onResume (VideoFragment.java:398)
androidx.fragment.app.Fragment.performResume (Fragment.java:2748)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832
```

```
Fatal Exception: java.lang.UnsupportedOperationException
eglCreateWindowSurface() can only be called with an instance of Surface, SurfaceView, SurfaceTexture or SurfaceHolder at the moment, this will be fixed later.
android.opengl.EGL14.eglCreateWindowSurface (EGL14.java:268)
com.time.fog.base.view.RecordableSurfaceView$ARRenderThread.run (RecordableSurfaceView.java:554)
```
```

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.time.fog.base.gl.VideoRenderer.setSurfaceTexture(android.graphics.SurfaceTexture)' on a null object reference
com.time.fog.fragments.VideoFragment.startPreview (VideoFragment.java:786)
com.time.fog.fragments.VideoFragment.access$700 (VideoFragment.java:91)
com.time.fog.fragments.VideoFragment$7.onOpened (VideoFragment.java:715)
android.hardware.camera2.impl.CameraDeviceImpl$1.run (CameraDeviceImpl.java:148)
android.os.HandlerThread.run (HandlerThread.java:65)
```

**Comment by EAStudios** [comment]
replay on this issue @spaceLenny, because I have this issue too.
